# Generated by Django 5.0.6 on 2024-07-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_typingtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
